# Generated by Django 4.2.3 on 2023-07-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('mail', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('contact', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('objet', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='theme_biblique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='type_annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_annonce', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_quote', models.CharField(max_length=2000)),
                ('verset', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('themes', models.ManyToManyField(to='dash.theme_biblique')),
            ],
        ),
        migrations.CreateModel(
            name='priere_louange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verset', models.CharField(max_length=500)),
                ('lien_yt', models.CharField(blank=True, max_length=500)),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('louange', 'louange'), ('priere', 'priere')], default='louange', max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.theme_biblique')),
            ],
        ),
        migrations.CreateModel(
            name='pensee_biblique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('lien_youtube', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.theme_biblique')),
            ],
        ),
        migrations.CreateModel(
            name='lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='images_upload/lifestyle')),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('themes', models.ManyToManyField(to='dash.theme_biblique')),
            ],
        ),
        migrations.CreateModel(
            name='etude_biblique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('sous_titre', models.CharField(max_length=500)),
                ('verset', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
                ('lien_yt', models.CharField(blank=True, max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('themes', models.ManyToManyField(to='dash.theme_biblique')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('validé', 'validé'), ('pre-validé', 'pre-validé'), ('non-validé', 'non-validé')], default='non-valider', max_length=500)),
                ('id_sujet', models.IntegerField()),
                ('table', models.CharField(choices=[('etude_biblique', 'etude_biblique'), ('pensee_biblique', 'pensee_biblique'), ('lifestyle', 'lifestyle')], default='etude_biblique', max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('txt_annonce', models.TextField()),
                ('image_annonce', models.ImageField(upload_to='images_upload/annonce')),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('type_annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.type_annonce')),
            ],
        ),
    ]
