# Generated by Django 4.2.3 on 2023-07-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sld_chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('montant', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('type_annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.type_annonce')),
            ],
        ),
    ]
